"""mpmgame public API."""

from .core import (
    AttackAction,
    DefenseAction,
    GameResult,
    rank1_mask,
    defense_cost,
    enumerate_rank1_masks,
    admissible_defenses,
    union_masks,
    intersect_masks,
    complement_mask,
    is_subset_mask,
    mask_footprint,
    tf_matrix,
    hadamard_mask_delta,
    masked_model_map,
    attack_sum,
    closed_loop_interconnection,
    is_destabilizing,
    utility,
    attack_success_set,
    defense_success_set,
    compute_success_sets,
    dominated_attacks,
    dominated_defenses,
    eliminate_dominated_strategies,
    payoff_matrix,
    expected_utility,
    solve_zero_sum_game,
)
from .examples import paper_example_data, run_paper_example, coordinated_attack_defeats_all
from .plotting import plot_success_bipartite_graph, plot_payoff_heatmap

__all__ = [
    "AttackAction",
    "DefenseAction",
    "GameResult",
    "rank1_mask",
    "defense_cost",
    "enumerate_rank1_masks",
    "admissible_defenses",
    "union_masks",
    "intersect_masks",
    "complement_mask",
    "is_subset_mask",
    "mask_footprint",
    "tf_matrix",
    "hadamard_mask_delta",
    "masked_model_map",
    "attack_sum",
    "closed_loop_interconnection",
    "is_destabilizing",
    "utility",
    "attack_success_set",
    "defense_success_set",
    "compute_success_sets",
    "dominated_attacks",
    "dominated_defenses",
    "eliminate_dominated_strategies",
    "payoff_matrix",
    "expected_utility",
    "solve_zero_sum_game",
    "paper_example_data",
    "run_paper_example",
    "coordinated_attack_defeats_all",
    "plot_success_bipartite_graph",
    "plot_payoff_heatmap",
]
