"""mpmgame public API."""

from .core import (
    AttackAction,
    DefenseAction,
    GameResult,
    rank1_mask,
    defense_cost,
    enumerate_rank1_masks,
    admissible_defenses,
    union_masks,
    intersect_masks,
    complement_mask,
    is_subset_mask,
    mask_footprint,
    tf_matrix,
    hadamard_mask_delta,
    masked_model_map,
    attack_sum,
    closed_loop_interconnection,
    is_destabilizing,
    utility,
    attack_success_set,
    defense_success_set,
    compute_success_sets,
    dominated_attacks,
    dominated_defenses,
    eliminate_dominated_strategies,
    payoff_matrix,
    expected_utility,
    solve_zero_sum_game,
)
from .examples import paper_example_data, run_paper_example, coordinated_attack_defeats_all
from .plotting import plot_success_bipartite_graph, plot_payoff_heatmap

__all__ = [
    "AttackAction",
    "DefenseAction",
    "GameResult",
    "rank1_mask",
    "defense_cost",
    "enumerate_rank1_masks",
    "admissible_defenses",
    "union_masks",
    "intersect_masks",
    "complement_mask",
    "is_subset_mask",
    "mask_footprint",
    "tf_matrix",
    "hadamard_mask_delta",
    "masked_model_map",
    "attack_sum",
    "closed_loop_interconnection",
    "is_destabilizing",
    "utility",
    "attack_success_set",
    "defense_success_set",
    "compute_success_sets",
    "dominated_attacks",
    "dominated_defenses",
    "eliminate_dominated_strategies",
    "payoff_matrix",
    "expected_utility",
    "solve_zero_sum_game",
    "paper_example_data",
    "run_paper_example",
    "coordinated_attack_defeats_all",
    "plot_success_bipartite_graph",
    "plot_payoff_heatmap",

    "ContractSystem",
    "VulnerabilityResult",
    "build_contract_system",
    "make_realization",
    "make_realization_dynamic",
    "make_realization_checked",
    "compute_gamma",
    "compute_attack_map",
    "access_matrix",
    "vulnerability_full",
    "vulnerability_single_link",
    "BoundResult",
    "bound_upper_full",
    "bound_lower_single_link",
    "bound_lower_full",
    "FamilyResult",
    "family_vary_q",
    "family_vary_alpha",
    "family_vary_access",
    "summarize_experiment_results",
    "export_report_markdown",
    "random_bound_experiments",
    "projection_design",
    "projection_iteration",
    "ProjectionDesignResult",
    "lp_relaxation_design",
    "LPDesignResult",
    "plot_vulnerability_vs_parameter",
    "plot_bound_scatter",
    "plot_projection_convergence",
    "plot_design_comparison",
    "plot_access_model_comparison",
    "ProblemSpec",
    "ParameterizationSpec",
    "EvalResult",
    "OptimizationResult",
    "evaluate_theta",
    "theta_to_q",
    "q_to_theta",
    "theta_dim",
    "DynamicQ",
    "serialize_dynamic_q_for_row",
    "deserialize_dynamic_q_from_row",
    "optimize_with_algorithm",
    "REQUIRED_ALGORITHMS",
    "OPTIONAL_ALGORITHMS",
    "benchmark_problem_registry",
    "run_benchmark_suite",
    "load_raw_results",
    "summarize_row_realization",
    "rows_have_same_contracted_subsystem",
    "realization_markdown",
    "write_realization_markdown_from_csv",
]


from .fmp import (
    ContractSystem,
    VulnerabilityResult,
    build_contract_system,
    make_realization,
    make_realization_dynamic,
    make_realization_checked,
    compute_gamma,
    compute_attack_map,
    access_matrix,
    vulnerability_full,
    vulnerability_single_link,
)
from .bounds import (
    BoundResult,
    bound_upper_full,
    bound_lower_single_link,
    bound_lower_full,
)
from .experiments_ch2 import (
    FamilyResult,
    family_vary_q,
    family_vary_alpha,
    family_vary_access,
    summarize_experiment_results,
    export_report_markdown,
)
from .random_systems import random_bound_experiments
from .design_projection import projection_design, projection_iteration, ProjectionDesignResult
from .design_lp import lp_relaxation_design, LPDesignResult
from .plotting_ch2 import (
    plot_vulnerability_vs_parameter,
    plot_bound_scatter,
    plot_projection_convergence,
    plot_design_comparison,
    plot_access_model_comparison,
)


from .objective_engine import (
    ProblemSpec,
    ParameterizationSpec,
    EvalResult,
    OptimizationResult,
    evaluate_theta,
    theta_to_q,
    q_to_theta,
    theta_dim,
)
from .dsf_param import DynamicQ, serialize_dynamic_q_for_row, deserialize_dynamic_q_from_row
from .optimize_nonlinear import optimize_with_algorithm, REQUIRED_ALGORITHMS, OPTIONAL_ALGORITHMS
from .benchmark_suite import benchmark_problem_registry, run_benchmark_suite
from .realization_report import (
    load_raw_results,
    summarize_row_realization,
    rows_have_same_contracted_subsystem,
    realization_markdown,
    write_realization_markdown_from_csv,
)
